import React, { useState } from 'react';
import { Head, Link, router } from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import {
    Award,
    Printer,
    ShieldCheck,
    CheckCircle2,
    Lock,
    Key,
    ArrowLeft,
    FileText,
    Users,
    Building2,
    Sparkles
} from 'lucide-react';

export default function Show({ authority, case_data, calculation, nominees }) {
    const [signModalOpen, setSignModalOpen] = useState(false);
    const [pin, setPin] = useState('');
    const [token, setToken] = useState('ePass2003 / Auto Token');
    const [isSigning, setIsSigning] = useState(false);
    const [signSuccess, setSignSuccess] = useState(false);

    const handleDscSign = async (e) => {
        e.preventDefault();
        setIsSigning(true);

        // Simulated Cryptographic PKCS#7 block generated by Hardware USB Token
        const dummySignedHash = 'MIIF5AYJKoZIhvcNAQcCoIIF1TCCBdECAQExDTALBglghkgBZQMEAgEwggNKBgkqhkiG9w0BBwGgggM...PKCS7_SIGNED_' + Date.now();

        try {
            const res = await fetch(`/authority/${authority.id}/sign`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]')?.getAttribute('content') || '',
                },
                body: JSON.stringify({
                    signed_hash: dummySignedHash,
                    certificate_serial: 'DSC-CAG-TRIPURA-' + Math.floor(100000 + Math.random() * 900000),
                    certificate_issuer: 'eMudhra CA / National Informatics Centre (NIC)',
                    certificate_valid_to: '2028-12-31',
                }),
            });

            if (res.ok) {
                setSignSuccess(true);
                setTimeout(() => {
                    setSignModalOpen(false);
                    router.reload();
                }, 1000);
            }
        } catch (err) {
            console.error('Signing failed', err);
        } finally {
            setIsSigning(false);
        }
    };

    return (
        <AuthenticatedLayout title={`Authority - ${authority.authority_number}`}>
            <Head title={`Authority Order - ${authority.authority_number}`} />

            <div className="space-y-6 max-w-4xl mx-auto">
                {/* Header & Actions */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                    <div className="flex items-center gap-3">
                        <Link
                            href="/authority"
                            className="p-2 rounded-xl bg-slate-900 border border-slate-800 text-slate-400 hover:text-white transition"
                        >
                            <ArrowLeft className="w-4 h-4" />
                        </Link>
                        <div>
                            <div className="flex items-center gap-2">
                                <h2 className="text-xl font-bold tracking-tight text-white font-mono">
                                    {authority.authority_number}
                                </h2>
                                {authority.is_signed ? (
                                    <span className="px-2.5 py-0.5 text-[10px] font-semibold rounded-full bg-teal-500/10 text-teal-300 border border-teal-500/20 flex items-center gap-1">
                                        <ShieldCheck className="w-3 h-3 text-teal-400" />
                                        <span>Digitally Signed</span>
                                    </span>
                                ) : (
                                    <span className="px-2.5 py-0.5 text-[10px] font-semibold rounded-full bg-amber-500/10 text-amber-400 border border-amber-500/20">
                                        Pending Digital Signature
                                    </span>
                                )}
                            </div>
                            <p className="text-xs text-slate-400">
                                Case: <strong className="text-slate-200 font-mono">{case_data.registration_no}</strong> &bull; Date: {authority.authority_date}
                            </p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3">
                        {!authority.is_signed && (
                            <button
                                type="button"
                                onClick={() => setSignModalOpen(true)}
                                className="inline-flex items-center gap-2 px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-lg shadow-emerald-600/25 transition"
                            >
                                <Key className="w-4 h-4" />
                                <span>Sign with USB DSC Token</span>
                            </button>
                        )}

                        <a
                            href={`/authority/${authority.id}/print`}
                            target="_blank"
                            rel="noreferrer"
                            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold shadow-lg shadow-indigo-600/20 transition"
                        >
                            <Printer className="w-4 h-4" />
                            <span>Print Authority Letter</span>
                        </a>
                    </div>
                </div>

                {/* Printable Document Preview Card */}
                <div className="glass-panel p-8 rounded-2xl space-y-6 border border-slate-800">
                    {/* Header */}
                    <div className="text-center border-b border-slate-800/80 pb-4">
                        <div className="text-xs font-bold text-slate-400 uppercase tracking-widest">
                            Government of India • Comptroller and Auditor General
                        </div>
                        <h1 className="text-base font-bold text-white mt-1">
                            OFFICE OF THE ACCOUNTANT GENERAL (A & E), TRIPURA ::: AGARTALA
                        </h1>
                        <p className="text-[11px] text-slate-400">
                            General Provident Fund Final Payment Order & Disbursement Authority
                        </p>
                    </div>

                    {/* Meta info */}
                    <div className="grid grid-cols-2 gap-4 text-xs">
                        <div>
                            <span className="text-slate-500">Subscriber Name:</span>
                            <div className="font-semibold text-slate-100 mt-0.5">
                                {case_data.name_title} {case_data.subscriber_name_cache}
                            </div>
                            <div className="text-slate-400 text-[11px]">{case_data.designation}</div>
                        </div>

                        <div className="text-right">
                            <span className="text-slate-500">GPF Account Number:</span>
                            <div className="font-mono font-bold text-indigo-300 mt-0.5">
                                {case_data.formatted_gpf_account}
                            </div>
                            <div className="text-slate-400 text-[11px]">DDO: {case_data.ddo_code}</div>
                        </div>
                    </div>

                    {(case_data.case_type === 'FAM' || case_data.case_type === 'D' || String(case_data.pension_type_id) === '2') && (
                        <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-xs text-rose-300">
                            <span className="font-bold text-rose-200">Family Pension Disbursement: </span>
                            Authorized to {case_data.spouse_name ? `${case_data.spouse_name} (${case_data.spouse_relation || 'Spouse'})` : 'designated legal nominee(s)'} of Late {case_data.subscriber_name_cache}.
                        </div>
                    )}

                    {/* Financial Summary */}
                    <div className="rounded-xl overflow-hidden border border-slate-800">
                        <table className="w-full text-left text-xs">
                            <thead className="bg-slate-900/80 border-b border-slate-800 text-slate-400 font-semibold">
                                <tr>
                                    <th className="py-2.5 px-4">Financial Ledger Component</th>
                                    <th className="py-2.5 px-4 text-right">Amount (₹)</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-slate-800/60 font-mono">
                                <tr>
                                    <td className="py-2 px-4 text-slate-300">Opening Principal Balance</td>
                                    <td className="py-2 px-4 text-right text-slate-200 font-semibold">
                                        ₹ {Number(calculation?.opening_balance_amount || 0).toLocaleString('en-IN')}
                                    </td>
                                </tr>
                                <tr>
                                    <td className="py-2 px-4 text-slate-300">Subscriptions & Verified Deposits</td>
                                    <td className="py-2 px-4 text-right text-emerald-400 font-semibold">
                                        + ₹ {Number(calculation?.total_subscriptions || 0).toLocaleString('en-IN')}
                                    </td>
                                </tr>
                                <tr>
                                    <td className="py-2 px-4 text-slate-300">Statutory Interest Computed</td>
                                    <td className="py-2 px-4 text-right text-indigo-400 font-semibold">
                                        + ₹ {Number(calculation?.total_interest_computed || 0).toLocaleString('en-IN')}
                                    </td>
                                </tr>
                                <tr>
                                    <td className="py-2 px-4 text-slate-300">Withdrawals during Year</td>
                                    <td className="py-2 px-4 text-right text-rose-400 font-semibold">
                                        - ₹ {Number(calculation?.total_withdrawals || 0).toLocaleString('en-IN')}
                                    </td>
                                </tr>
                                {calculation?.dlis_amount > 0 && (
                                    <tr>
                                        <td className="py-2 px-4 text-slate-300">DLIS Insurance Amount</td>
                                        <td className="py-2 px-4 text-right text-amber-400 font-semibold">
                                            + ₹ {Number(calculation.dlis_amount).toLocaleString('en-IN')}
                                        </td>
                                    </tr>
                                )}
                                <tr className="bg-slate-900/60 font-sans">
                                    <td className="py-3 px-4 text-sm font-bold text-slate-100">CERTIFIED NET PAYABLE BALANCE</td>
                                    <td className="py-3 px-4 text-right text-base font-extrabold text-emerald-400 font-mono">
                                        ₹ {Number(authority.net_amount).toLocaleString('en-IN')}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    {/* Nominees */}
                    {nominees && nominees.length > 0 && (
                        <div className="space-y-2">
                            <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider">
                                Legal Claimants & Nominee Distribution
                            </h4>
                            <div className="rounded-xl overflow-hidden border border-slate-800">
                                <table className="w-full text-left text-xs">
                                    <thead className="bg-slate-900/60 text-slate-400 font-semibold">
                                        <tr>
                                            <th className="py-2 px-3">Nominee Name</th>
                                            <th className="py-2 px-3">Relation</th>
                                            <th className="py-2 px-3">Share %</th>
                                            <th className="py-2 px-3 text-right">Allocated Amount</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-800/60">
                                        {nominees.map((n) => (
                                            <tr key={n.id}>
                                                <td className="py-2 px-3 font-semibold text-slate-200">{n.nominee_name}</td>
                                                <td className="py-2 px-3 text-slate-400">{n.relationship}</td>
                                                <td className="py-2 px-3 font-mono">{n.share_percentage}%</td>
                                                <td className="py-2 px-3 text-right font-mono font-bold text-emerald-400">
                                                    ₹ {Number(n.allocated_amount).toLocaleString('en-IN')}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )}

                    {/* Digital Signature Seal */}
                    <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
                        <div className="text-[10px] text-slate-500 font-mono">
                            SHA-256 Digest: {authority.verification_hash || 'Pending signature generation'}
                        </div>

                        {authority.is_signed && authority.digital_signature && (
                            <div className="p-3 rounded-xl bg-teal-500/10 border border-teal-500/30 text-teal-300 text-xs flex items-center gap-3">
                                <ShieldCheck className="w-6 h-6 text-teal-400" />
                                <div>
                                    <div className="font-bold">Digitally Certified by Senior Accounts Officer</div>
                                    <div className="text-[11px] text-teal-400/80">
                                        {authority.digital_signature.signatory_name} &bull; {authority.digital_signature.certificate_serial}
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>
                </div>

                {/* USB DSC Token Handshake Modal */}
                {signModalOpen && (
                    <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fadeIn">
                        <div className="glass-panel max-w-md w-full p-6 rounded-2xl border border-slate-800 space-y-5">
                            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                                <h3 className="text-sm font-bold text-white flex items-center gap-2">
                                    <Key className="w-4 h-4 text-emerald-400" />
                                    <span>Hardware USB Token (DSC) Handshake</span>
                                </h3>
                                <button
                                    onClick={() => setSignModalOpen(false)}
                                    className="text-slate-500 hover:text-white"
                                >
                                    &times;
                                </button>
                            </div>

                            <p className="text-xs text-slate-400">
                                Connect your authorized USB Crypto Token (ePass2003 / Watchdata) to certify this payment order.
                            </p>

                            <form onSubmit={handleDscSign} className="space-y-4">
                                <div>
                                    <label className="block text-xs font-medium text-slate-300 mb-1">
                                        Detected Token / Certificate
                                    </label>
                                    <select
                                        value={token}
                                        onChange={(e) => setToken(e.target.value)}
                                        className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs text-slate-100"
                                    >
                                        <option value="ePass2003 / Auto Token">ePass2003 - Sr. Accounts Officer (Valid till 2028)</option>
                                        <option value="NIC Crypto Token">NIC Standard Token - Treasury Cell</option>
                                    </select>
                                </div>

                                <div>
                                    <label className="block text-xs font-medium text-slate-300 mb-1">
                                        Token User PIN <span className="text-rose-400">*</span>
                                    </label>
                                    <input
                                        type="password"
                                        value={pin}
                                        onChange={(e) => setPin(e.target.value)}
                                        placeholder="••••••••"
                                        className="w-full px-3 py-2 bg-slate-900 border border-slate-700 rounded-xl text-xs text-slate-100 font-mono tracking-widest"
                                        required
                                    />
                                </div>

                                <div className="flex items-center justify-end gap-3 pt-2">
                                    <button
                                        type="button"
                                        onClick={() => setSignModalOpen(false)}
                                        className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-xs font-semibold text-slate-300"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="submit"
                                        disabled={isSigning || pin.length < 4}
                                        className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold shadow-lg shadow-emerald-600/25 disabled:opacity-50 flex items-center gap-2"
                                    >
                                        {isSigning ? (
                                            <>
                                                <Sparkles className="w-3.5 h-3.5 animate-spin" />
                                                <span>Signing Document...</span>
                                            </>
                                        ) : (
                                            <>
                                                <ShieldCheck className="w-3.5 h-3.5" />
                                                <span>Apply PKCS#7 Signature</span>
                                            </>
                                        )}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                )}
            </div>
        </AuthenticatedLayout>
    );
}
